//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatLibreria.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Editorial { get; set; }
        public string Edicion { get; set; }
        public string ISBN { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
